# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: "path/to/go.mod"

      - name: Build
        run: go build -v ./...

      - run: "go vet ./..."
      - uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2025.1.1"

      - name: Test
        run: go test -v ./...
